[build]
  command = "hugo"      # Hugo'nun build komutu
  publish = "public"    # Hugo tarafından oluşturulan çıkış dizini
  functions = "netlify/functions"  # Fonksiyon dosyalarının bulunduğu dizin

[context.production.environment]
  HUGO_VERSION = "0.89.4"  # (Opsiyonel) Hugo sürümünü belirtin
